database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:postgres}
  auth:
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:passwordnyaPostgres}
server:
  port: ${APPLICATION_PORT:8080}
  servlet:
    context-path: /@project.artifactId@
# spring configuration
spring:
  application:
    name: @project.artifactId@
    version: @project.version@
    fullname: @project.name@
  mvc:
    dispatch-options-request: true
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.auth.username}
    password: ${database.auth.password}
    driver-class-name: org.postgresql.Driver
  flyway:
    encoding: UTF-8
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
    clean-on-validation-error: true
    connect-retries: 3
    check-location: true
    user: ${database.auth.username}
    password: ${database.auth.password}
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.maryanto.dimas.example: ${LOG_LEVEL:DEBUG}
    org.springframework: DEBUG
  file: ${LOG_LOCATION:${spring.application.name}.log}
